package:
  name: dgl
  version: "0.1.3"

source:
  git_rev: 0.1.x
  git_url: https://github.com/dmlc/dgl.git

requirements:
  build:
    - python {{ python }}
    - setuptools
    - cmake
    - git
    - m2w64-gcc         # [win]
    - m2w64-make        # [win]
  run:
    - python
    - numpy
    - scipy
    - networkx

about:
  home: https://github.com/dmlc/dgl.git
  license_file: ../../LICENSE
